#ifndef QTERMWIDGET_EXPORT_H
#define QTERMWIDGET_EXPORT_H
#include <QtCore/qglobal.h>

#if defined(QTERMWIDGET_LIBRARY)
#define QTERMWIDGET_EXPORT Q_DECL_EXPORT
#else
#define QTERMWIDGET_EXPORT Q_DECL_IMPORT
#endif

// QTERMWIDGET_NO_EXPORT
#if defined(QTERMWIDGET_LIBRARY)
#define QTERMWIDGET_NO_EXPORT
#else
#define QTERMWIDGET_NO_EXPORT Q_DECL_IMPORT
#endif
#endif // QTERMWIDGET_EXPORT_H
